version: '3.7'

services:
    sonarserver:
        image: sonarqube
        ports:
            - 9001:9000
        networks:
            - sonarqube
    sonarscanner:
        build:
            context: ./docker/scanner
        networks:
            - sonarqube

networks:
    sonarqube:
        driver: bridge
